"""Initial migration"""
from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.create_table("users", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("telegram_id", sa.BigInteger, unique=True, index=True), sa.Column("public_id", sa.String(32), unique=True, index=True, nullable=False), sa.Column("username", sa.String(64)), sa.Column("first_name", sa.String(128)), sa.Column("last_name", sa.String(128)), sa.Column("nickname", sa.String(64)), sa.Column("gender", sa.String(16)), sa.Column("looking_for", sa.String(16), default="everyone"), sa.Column("birth_date", sa.Date), sa.Column("region", sa.String(64)), sa.Column("city", sa.String(64)), sa.Column("bio", sa.Text), sa.Column("interests", sa.JSON, default=list), sa.Column("photos", sa.JSON, default=list), sa.Column("language_code", sa.String(8), default="uz"), sa.Column("is_premium", sa.Boolean, default=False), sa.Column("premium_tier", sa.String(16)), sa.Column("is_verified", sa.Boolean, default=False), sa.Column("is_online", sa.Boolean, default=False), sa.Column("is_banned", sa.Boolean, default=False), sa.Column("is_profile_complete", sa.Boolean, default=False), sa.Column("is_boosted", sa.Boolean, default=False), sa.Column("boost_expires_at", sa.DateTime), sa.Column("likes_sent", sa.Integer, default=0), sa.Column("likes_sent_today", sa.Integer, default=0), sa.Column("likes_received", sa.Integer, default=0), sa.Column("match_count", sa.Integer, default=0), sa.Column("profile_views", sa.Integer, default=0), sa.Column("last_seen", sa.DateTime, default=sa.func.now()), sa.Column("created_at", sa.DateTime, default=sa.func.now()), sa.Column("updated_at", sa.DateTime, default=sa.func.now(), onupdate=sa.func.now()))
    op.create_index("ix_users_gender", "users", ["gender"])
    op.create_index("ix_users_region", "users", ["region"])

    op.create_table("profiles", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False), sa.Column("height_cm", sa.Integer), sa.Column("weight_kg", sa.Integer), sa.Column("occupation", sa.String(128)), sa.Column("education", sa.String(128)), sa.Column("zodiac", sa.String(16)), sa.Column("latitude", sa.Float), sa.Column("longitude", sa.Float), sa.Column("instagram", sa.String(64)), sa.Column("tiktok", sa.String(64)), sa.Column("created_at", sa.DateTime, default=sa.func.now()))

    op.create_table("likes", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("target_user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("action", sa.String(16), nullable=False), sa.Column("is_superlike", sa.Boolean, default=False), sa.Column("is_blocked", sa.Boolean, default=False), sa.Column("created_at", sa.DateTime, default=sa.func.now()), sa.UniqueConstraint("user_id", "target_user_id", name="uq_user_target"))

    op.create_table("matches", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user1_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("user2_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("chat_id", sa.BigInteger), sa.Column("is_active", sa.Boolean, default=True), sa.Column("unmatched_by", sa.BigInteger), sa.Column("created_at", sa.DateTime, default=sa.func.now()), sa.UniqueConstraint("user1_id", "user2_id", name="uq_match_pair"))

    op.create_table("chats", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user1_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("user2_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("match_id", sa.BigInteger, sa.ForeignKey("matches.id", ondelete="SET NULL")), sa.Column("last_message_at", sa.DateTime), sa.Column("is_muted_user1", sa.Boolean, default=False), sa.Column("is_muted_user2", sa.Boolean, default=False), sa.Column("created_at", sa.DateTime, default=sa.func.now()), sa.UniqueConstraint("user1_id", "user2_id", name="uq_chat_pair"))

    op.create_table("messages", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("chat_id", sa.BigInteger, sa.ForeignKey("chats.id", ondelete="CASCADE"), nullable=False), sa.Column("sender_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("type", sa.String(16), default="text"), sa.Column("content", sa.Text), sa.Column("media_url", sa.Text), sa.Column("media_thumb", sa.Text), sa.Column("reply_to_id", sa.BigInteger, sa.ForeignKey("messages.id", ondelete="SET NULL")), sa.Column("is_edited", sa.Boolean, default=False), sa.Column("is_deleted", sa.Boolean, default=False), sa.Column("read_at", sa.DateTime), sa.Column("created_at", sa.DateTime, default=sa.func.now()))

    op.create_table("media", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("type", sa.String(16), nullable=False), sa.Column("filename", sa.String(256), nullable=False), sa.Column("url", sa.Text, nullable=False), sa.Column("thumbnail_url", sa.Text), sa.Column("size_bytes", sa.BigInteger), sa.Column("content_type", sa.String(64)), sa.Column("width", sa.Integer), sa.Column("height", sa.Integer), sa.Column("duration", sa.Integer), sa.Column("sha256", sa.String(64)), sa.Column("is_nsfw", sa.Boolean, default=False), sa.Column("is_approved", sa.Boolean, default=True), sa.Column("created_at", sa.DateTime, default=sa.func.now()))

    op.create_table("notifications", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("type", sa.String(32), nullable=False), sa.Column("title", sa.String(256), nullable=False), sa.Column("body", sa.Text), sa.Column("data", sa.JSON, default=dict), sa.Column("is_read", sa.Boolean, default=False), sa.Column("read_at", sa.DateTime), sa.Column("created_at", sa.DateTime, default=sa.func.now()))

    op.create_table("premium", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("tier", sa.String(16), nullable=False), sa.Column("started_at", sa.DateTime, default=sa.func.now()), sa.Column("expires_at", sa.DateTime, nullable=False), sa.Column("boost_count", sa.Integer, default=0), sa.Column("superlikes_used", sa.Integer, default=0), sa.Column("is_active", sa.Boolean, default=True), sa.Column("auto_renew", sa.Boolean, default=False))

    op.create_table("payments", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("tier", sa.String(16), nullable=False), sa.Column("amount_stars", sa.Integer, nullable=False), sa.Column("amount_usd", sa.Float, nullable=False), sa.Column("telegram_payment_charge_id", sa.String(256)), sa.Column("provider", sa.String(32), default="telegram_stars"), sa.Column("status", sa.String(16), default="pending"), sa.Column("created_at", sa.DateTime, default=sa.func.now()))

    op.create_table("reports", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("reporter_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("reported_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("reason", sa.String(32), nullable=False), sa.Column("description", sa.Text), sa.Column("status", sa.String(16), default="pending"), sa.Column("reviewed_by", sa.BigInteger), sa.Column("reviewed_at", sa.DateTime), sa.Column("action_taken", sa.String(32)), sa.Column("created_at", sa.DateTime, default=sa.func.now()))

    op.create_table("blocks", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("blocked_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("reason", sa.String(64)), sa.Column("created_at", sa.DateTime, default=sa.func.now()), sa.UniqueConstraint("user_id", "blocked_id", name="uq_block_pair"))

    op.create_table("audit_logs", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger), sa.Column("action", sa.String(64), nullable=False), sa.Column("resource_type", sa.String(32)), sa.Column("resource_id", sa.String(64)), sa.Column("details", sa.JSON, default=dict), sa.Column("ip_address", sa.String(64)), sa.Column("user_agent", sa.Text), sa.Column("created_at", sa.DateTime, default=sa.func.now()))


def downgrade():
    for table in ["audit_logs", "blocks", "reports", "payments", "premium", "notifications", "media", "messages", "chats", "matches", "likes", "profiles", "users"]:
        op.drop_table(table)
