"""Mega migration - all new tables
Revision ID: 002_mega
Revises: 001_initial
Create Date: 2026-07-14
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import JSON, JSONB


revision = "002_mega"
down_revision = "001_initial"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Story
    op.create_table("stories", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("media_type", sa.String(16), nullable=False), sa.Column("media_url", sa.Text, nullable=False), sa.Column("thumbnail_url", sa.Text), sa.Column("text_overlay", sa.Text), sa.Column("background_color", sa.String(16), server_default="#000000"), sa.Column("duration", sa.Integer, server_default="5"), sa.Column("views_count", sa.Integer, server_default="0"), sa.Column("is_highlight", sa.Boolean, server_default=sa.text("false")), sa.Column("expires_at", sa.DateTime, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("story_views", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("story_id", sa.BigInteger, sa.ForeignKey("stories.id", ondelete="CASCADE"), nullable=False), sa.Column("viewer_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("story_reactions", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("story_id", sa.BigInteger, sa.ForeignKey("stories.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("reaction", sa.String(16), nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("story_replies", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("story_id", sa.BigInteger, sa.ForeignKey("stories.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("content", sa.Text, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))

    # Gamification
    op.create_table("coin_transactions", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("amount", sa.Integer, nullable=False), sa.Column("type", sa.String(32), nullable=False), sa.Column("reason", sa.String(128)), sa.Column("ref_id", sa.BigInteger), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("achievements", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("code", sa.String(64), unique=True, nullable=False), sa.Column("name", sa.String(128), nullable=False), sa.Column("description", sa.Text), sa.Column("icon", sa.String(16)), sa.Column("reward_coins", sa.Integer, server_default="0"), sa.Column("condition_type", sa.String(32)), sa.Column("condition_value", sa.Integer, server_default="1"), sa.Column("tier", sa.String(16), server_default="bronze"))
    op.create_table("user_achievements", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("achievement_id", sa.Integer, sa.ForeignKey("achievements.id", ondelete="CASCADE"), nullable=False), sa.Column("progress", sa.Integer, server_default="0"), sa.Column("unlocked_at", sa.DateTime), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("streaks", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False), sa.Column("current_streak", sa.Integer, server_default="0"), sa.Column("longest_streak", sa.Integer, server_default="0"), sa.Column("last_login", sa.Date), sa.Column("total_logins", sa.Integer, server_default="0"))
    op.create_table("missions", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("code", sa.String(64), unique=True, nullable=False), sa.Column("name", sa.String(128), nullable=False), sa.Column("description", sa.Text), sa.Column("type", sa.String(32)), sa.Column("target", sa.Integer, server_default="1"), sa.Column("reward_coins", sa.Integer, server_default="0"), sa.Column("reward_superlikes", sa.Integer, server_default="0"), sa.Column("reward_boost", sa.Integer, server_default="0"))
    op.create_table("user_missions", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("mission_id", sa.Integer, sa.ForeignKey("missions.id", ondelete="CASCADE"), nullable=False), sa.Column("progress", sa.Integer, server_default="0"), sa.Column("target", sa.Integer, server_default="1"), sa.Column("is_completed", sa.Boolean, server_default=sa.text("false")), sa.Column("completed_at", sa.DateTime), sa.Column("expires_at", sa.DateTime, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("gifts", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("code", sa.String(64), unique=True, nullable=False), sa.Column("name", sa.String(128), nullable=False), sa.Column("icon", sa.String(16), server_default="🎁"), sa.Column("image_url", sa.Text), sa.Column("price_coins", sa.Integer, nullable=False), sa.Column("animation_url", sa.Text), sa.Column("category", sa.String(32), server_default="general"))
    op.create_table("gift_transactions", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("sender_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("recipient_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("gift_id", sa.Integer, sa.ForeignKey("gifts.id", ondelete="CASCADE"), nullable=False), sa.Column("chat_id", sa.BigInteger), sa.Column("message", sa.Text), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("spin_rewards", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("reward_type", sa.String(32)), sa.Column("reward_value", sa.Integer, server_default="0"), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("leaderboard", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False), sa.Column("total_score", sa.Integer, server_default="0"), sa.Column("matches", sa.Integer, server_default="0"), sa.Column("messages_sent", sa.Integer, server_default="0"), sa.Column("photos_uploaded", sa.Integer, server_default="0"), sa.Column("days_active", sa.Integer, server_default="0"), sa.Column("rank", sa.Integer, server_default="0"), sa.Column("updated_at", sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now()))

    # Personality
    op.create_table("personality_tests", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("mbti_type", sa.String(8)), sa.Column("big_five", JSONB), sa.Column("love_language", sa.String(32)), sa.Column("answers", JSONB), sa.Column("completed", sa.Boolean, server_default=sa.text("false")), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("prompts", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("question", sa.Text, nullable=False), sa.Column("category", sa.String(32), server_default="general"), sa.Column("placeholder", sa.String(256)), sa.Column("is_active", sa.Boolean, server_default=sa.text("true")), sa.Column("order", sa.Integer, server_default="0"))
    op.create_table("user_prompts", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("prompt_id", sa.Integer, sa.ForeignKey("prompts.id", ondelete="CASCADE"), nullable=False), sa.Column("answer", sa.Text, nullable=False), sa.Column("order", sa.Integer, server_default="0"))
    op.create_table("top_fives", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False), sa.Column("movies", JSONB), sa.Column("songs", JSONB), sa.Column("books", JSONB), sa.Column("foods", JSONB), sa.Column("travel", JSONB), sa.Column("updated_at", sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now()))
    op.create_table("voice_intros", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False), sa.Column("audio_url", sa.Text, nullable=False), sa.Column("duration", sa.Integer, server_default="0"), sa.Column("transcript", sa.Text), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("video_intros", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False), sa.Column("video_url", sa.Text, nullable=False), sa.Column("thumbnail_url", sa.Text), sa.Column("duration", sa.Integer, server_default="0"), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("social_links", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False), sa.Column("instagram", sa.String(64)), sa.Column("tiktok", sa.String(64)), sa.Column("spotify", sa.String(128)), sa.Column("telegram", sa.String(64)), sa.Column("twitter", sa.String(64)), sa.Column("youtube", sa.String(128)), sa.Column("linkedin", sa.String(128)), sa.Column("website", sa.String(256)))
    op.create_table("lifestyle_tags", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("code", sa.String(32), unique=True, nullable=False), sa.Column("name", sa.String(64), nullable=False), sa.Column("icon", sa.String(8)), sa.Column("category", sa.String(32), server_default="lifestyle"))
    op.create_table("user_lifestyle_tags", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("tag_id", sa.Integer, sa.ForeignKey("lifestyle_tags.id", ondelete="CASCADE"), nullable=False))

    # Safety
    op.create_table("photo_verifications", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("selfie_url", sa.Text, nullable=False), sa.Column("reference_photo_id", sa.BigInteger, nullable=False), sa.Column("status", sa.String(16), server_default="pending"), sa.Column("confidence", sa.Float, server_default="0"), sa.Column("verified_at", sa.DateTime), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("two_factor_auth", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False), sa.Column("enabled", sa.Boolean, server_default=sa.text("false")), sa.Column("secret", sa.String(64)), sa.Column("backup_codes", JSONB), sa.Column("last_used", sa.DateTime))
    op.create_table("emergency_contacts", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("name", sa.String(128), nullable=False), sa.Column("phone", sa.String(32), nullable=False), sa.Column("relation", sa.String(32)), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("safety_reports", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("reporter_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("reported_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("chat_id", sa.BigInteger), sa.Column("message_id", sa.BigInteger), sa.Column("reason", sa.String(64), nullable=False), sa.Column("evidence", JSONB), sa.Column("description", sa.Text), sa.Column("status", sa.String(16), server_default="pending"), sa.Column("reviewed_by", sa.BigInteger), sa.Column("reviewed_at", sa.DateTime), sa.Column("action_taken", sa.String(64)), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("panic_events", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("location_lat", sa.Float), sa.Column("location_lon", sa.Float), sa.Column("contacted_id", sa.BigInteger), sa.Column("resolved", sa.Boolean, server_default=sa.text("false")), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("stalker_protection", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False), sa.Column("block_screenshots", sa.Boolean, server_default=sa.text("false")), sa.Column("block_location", sa.Boolean, server_default=sa.text("false")), sa.Column("block_forwarded", sa.Boolean, server_default=sa.text("false")), sa.Column("mask_gps", sa.Boolean, server_default=sa.text("false")), sa.Column("fake_lat", sa.Float), sa.Column("fake_lon", sa.Float))
    op.create_table("data_export_requests", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(16), server_default="pending"), sa.Column("download_url", sa.Text), sa.Column("expires_at", sa.DateTime), sa.Column("requested_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("date_plans", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("match_id", sa.BigInteger, sa.ForeignKey("matches.id", ondelete="CASCADE"), nullable=False), sa.Column("proposer_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.String(128), nullable=False), sa.Column("description", sa.Text), sa.Column("location_name", sa.String(256), nullable=False), sa.Column("location_lat", sa.Float), sa.Column("location_lon", sa.Float), sa.Column("planned_at", sa.DateTime, nullable=False), sa.Column("category", sa.String(32), server_default="general"), sa.Column("cost_estimate", sa.Integer, server_default="0"), sa.Column("status", sa.String(16), server_default="pending"), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("date_feedback", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("date_plan_id", sa.BigInteger, sa.ForeignKey("date_plans.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("rating", sa.Integer, server_default="0"), sa.Column("would_meet_again", sa.Boolean, server_default=sa.text("false")), sa.Column("comment", sa.Text), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))

    # Community
    op.create_table("groups", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("name", sa.String(128), nullable=False), sa.Column("slug", sa.String(64), unique=True, nullable=False), sa.Column("description", sa.Text), sa.Column("cover_url", sa.Text), sa.Column("icon", sa.String(16)), sa.Column("category", sa.String(32), server_default="general"), sa.Column("type", sa.String(16), server_default="public"), sa.Column("rules", sa.Text), sa.Column("member_count", sa.Integer, server_default="0"), sa.Column("is_verified", sa.Boolean, server_default=sa.text("false")), sa.Column("created_by", sa.BigInteger, sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("group_members", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("group_id", sa.BigInteger, sa.ForeignKey("groups.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("role", sa.String(16), server_default="member"), sa.Column("joined_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("group_posts", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("group_id", sa.BigInteger, sa.ForeignKey("groups.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("content", sa.Text, nullable=False), sa.Column("media_urls", JSONB), sa.Column("likes_count", sa.Integer, server_default="0"), sa.Column("comments_count", sa.Integer, server_default="0"), sa.Column("is_pinned", sa.Boolean, server_default=sa.text("false")), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("events", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("title", sa.String(256), nullable=False), sa.Column("description", sa.Text), sa.Column("cover_url", sa.Text), sa.Column("category", sa.String(32), server_default="meetup"), sa.Column("location_name", sa.String(256)), sa.Column("location_lat", sa.Float), sa.Column("location_lon", sa.Float), sa.Column("starts_at", sa.DateTime, nullable=False), sa.Column("ends_at", sa.DateTime, nullable=False), sa.Column("capacity", sa.Integer, server_default="0"), sa.Column("attendees_count", sa.Integer, server_default="0"), sa.Column("ticket_price", sa.Integer, server_default="0"), sa.Column("is_online", sa.Boolean, server_default=sa.text("false")), sa.Column("meeting_url", sa.String(512)), sa.Column("status", sa.String(16), server_default="upcoming"), sa.Column("created_by", sa.BigInteger, sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("event_attendees", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("event_id", sa.BigInteger, sa.ForeignKey("events.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("status", sa.String(16), server_default="going"), sa.Column("ticket_paid", sa.Integer, server_default="0"), sa.Column("joined_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("forum_threads", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("category", sa.String(64), nullable=False), sa.Column("title", sa.String(256), nullable=False), sa.Column("content", sa.Text, nullable=False), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("views", sa.Integer, server_default="0"), sa.Column("replies", sa.Integer, server_default="0"), sa.Column("is_pinned", sa.Boolean, server_default=sa.text("false")), sa.Column("is_locked", sa.Boolean, server_default=sa.text("false")), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("forum_replies", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("thread_id", sa.BigInteger, sa.ForeignKey("forum_threads.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("content", sa.Text, nullable=False), sa.Column("likes_count", sa.Integer, server_default="0"), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("live_streams", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("host_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("title", sa.String(256)), sa.Column("description", sa.Text), sa.Column("stream_url", sa.Text, nullable=False), sa.Column("thumbnail_url", sa.Text), sa.Column("visibility", sa.String(16), server_default="public"), sa.Column("viewers_count", sa.Integer, server_default="0"), sa.Column("is_live", sa.Boolean, server_default=sa.text("false")), sa.Column("started_at", sa.DateTime, server_default=sa.func.now()), sa.Column("ended_at", sa.DateTime), sa.Column("gifts_received", sa.Integer, server_default="0"))
    op.create_table("nft_avatars", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False), sa.Column("image_url", sa.Text, nullable=False), sa.Column("style", sa.String(32), server_default="anime"), sa.Column("prompt", sa.Text), sa.Column("ton_wallet", sa.String(128)), sa.Column("transaction_hash", sa.String(128)), sa.Column("is_listed", sa.Boolean, server_default=sa.text("false")), sa.Column("price", sa.Integer, server_default="0"), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("coin_packages", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("name", sa.String(64), nullable=False), sa.Column("coins", sa.Integer, nullable=False), sa.Column("bonus_coins", sa.Integer, server_default="0"), sa.Column("price_stars", sa.Integer, nullable=False), sa.Column("price_usd", sa.Float, nullable=False), sa.Column("is_popular", sa.Boolean, server_default=sa.text("false")), sa.Column("is_active", sa.Boolean, server_default=sa.text("true")))

    # Chat features
    op.create_table("sticker_packs", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("name", sa.String(128), nullable=False), sa.Column("description", sa.Text), sa.Column("cover_url", sa.Text), sa.Column("category", sa.String(32), server_default="general"), sa.Column("price_coins", sa.Integer, server_default="0"), sa.Column("is_free", sa.Boolean, server_default=sa.text("true")), sa.Column("is_animated", sa.Boolean, server_default=sa.text("false")), sa.Column("sticker_count", sa.Integer, server_default="0"), sa.Column("downloads", sa.Integer, server_default="0"), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("stickers", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("pack_id", sa.Integer, sa.ForeignKey("sticker_packs.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("emoji", sa.String(8)), sa.Column("image_url", sa.Text, nullable=False), sa.Column("order", sa.Integer, server_default="0"))
    op.create_table("user_sticker_packs", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("pack_id", sa.Integer, sa.ForeignKey("sticker_packs.id", ondelete="CASCADE"), nullable=False))
    op.create_table("message_reactions", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("message_id", sa.BigInteger, sa.ForeignKey("messages.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("emoji", sa.String(8), nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("chat_themes", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("name", sa.String(64), nullable=False), sa.Column("code", sa.String(32), unique=True, nullable=False), sa.Column("background_url", sa.Text), sa.Column("bubble_color_user", sa.String(16)), sa.Column("bubble_color_other", sa.String(16)), sa.Column("text_color", sa.String(16)), sa.Column("preview_url", sa.Text), sa.Column("price_coins", sa.Integer, server_default="0"), sa.Column("is_free", sa.Boolean, server_default=sa.text("true")), sa.Column("is_seasonal", sa.Boolean, server_default=sa.text("false")))
    op.create_table("user_chat_themes", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("chat_id", sa.BigInteger), sa.Column("theme_id", sa.Integer, sa.ForeignKey("chat_themes.id", ondelete="CASCADE"), nullable=False), sa.Column("is_active", sa.Boolean, server_default=sa.text("true")))
    op.create_table("scheduled_messages", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("chat_id", sa.BigInteger, sa.ForeignKey("chats.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("sender_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("type", sa.String(16), server_default="text"), sa.Column("content", sa.Text), sa.Column("media_url", sa.Text), sa.Column("send_at", sa.DateTime, nullable=False), sa.Column("is_sent", sa.Boolean, server_default=sa.text("false")), sa.Column("sent_at", sa.DateTime), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("polls", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("chat_id", sa.BigInteger, sa.ForeignKey("chats.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("creator_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("question", sa.String(256), nullable=False), sa.Column("options", JSONB, nullable=False), sa.Column("is_multi", sa.Boolean, server_default=sa.text("false")), sa.Column("expires_at", sa.DateTime), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("poll_votes", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("poll_id", sa.BigInteger, sa.ForeignKey("polls.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("option_index", sa.Integer, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("pinned_messages", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("chat_id", sa.BigInteger, sa.ForeignKey("chats.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("message_id", sa.BigInteger, sa.ForeignKey("messages.id", ondelete="CASCADE"), nullable=False), sa.Column("pinned_by", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("pinned_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("saved_messages", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("message_id", sa.BigInteger, sa.ForeignKey("messages.id", ondelete="CASCADE"), nullable=False), sa.Column("saved_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("forwarded_messages", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("message_id", sa.BigInteger, sa.ForeignKey("messages.id", ondelete="CASCADE"), nullable=False), sa.Column("from_user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("from_chat_id", sa.BigInteger))

    # Advanced
    op.create_table("calls", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("chat_id", sa.BigInteger, sa.ForeignKey("chats.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("caller_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("callee_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("type", sa.String(16), nullable=False), sa.Column("status", sa.String(16), server_default="ringing"), sa.Column("channel_name", sa.String(128), nullable=False), sa.Column("started_at", sa.DateTime, server_default=sa.func.now()), sa.Column("answered_at", sa.DateTime), sa.Column("ended_at", sa.DateTime), sa.Column("duration", sa.Integer, server_default="0"), sa.Column("cost_coins", sa.Integer, server_default="0"), sa.Column("recording_url", sa.Text))
    op.create_table("photo_scores", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("photo_url", sa.String(512), nullable=False), sa.Column("ai_score", sa.Float, server_default="0"), sa.Column("likes_received", sa.Integer, server_default="0"), sa.Column("is_best_photo", sa.Boolean, server_default=sa.text("false")), sa.Column("order", sa.Integer, server_default="0"), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("compatibility_scores", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user1_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("user2_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("overall_score", sa.Float, server_default="0"), sa.Column("interest_score", sa.Float, server_default="0"), sa.Column("age_score", sa.Float, server_default="0"), sa.Column("location_score", sa.Float, server_default="0"), sa.Column("personality_score", sa.Float, server_default="0"), sa.Column("lifestyle_score", sa.Float, server_default="0"), sa.Column("details", JSONB), sa.Column("calculated_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("translation_cache", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("source_text", sa.Text, nullable=False), sa.Column("source_lang", sa.String(8), nullable=False), sa.Column("target_lang", sa.String(8), nullable=False), sa.Column("translated_text", sa.Text, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("ai_recommendations", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("target_user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("score", sa.Float, server_default="0"), sa.Column("reason", sa.Text), sa.Column("seen", sa.Boolean, server_default=sa.text("false")), sa.Column("clicked", sa.Boolean, server_default=sa.text("false")), sa.Column("matched", sa.Boolean, server_default=sa.text("false")), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("conversation_starters", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("text", sa.Text, nullable=False), sa.Column("category", sa.String(32), server_default="general"), sa.Column("language", sa.String(8), server_default="uz"), sa.Column("is_active", sa.Boolean, server_default=sa.text("true")), sa.Column("uses", sa.Integer, server_default="0"))
    op.create_table("sentiment_analysis", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("message_id", sa.BigInteger, sa.ForeignKey("messages.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("sentiment", sa.String(16)), sa.Column("score", sa.Float, server_default="0"), sa.Column("emotions", JSONB), sa.Column("is_toxic", sa.Boolean, server_default=sa.text("false")), sa.Column("toxicity_score", sa.Float, server_default="0"), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("chat_insights", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("chat_id", sa.BigInteger, sa.ForeignKey("chats.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("user1_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("user2_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("total_messages", sa.Integer, server_default="0"), sa.Column("response_time_avg", sa.Float, server_default="0"), sa.Column("sentiment_avg", sa.Float, server_default="0"), sa.Column("conversation_streak", sa.Integer, server_default="0"), sa.Column("last_message_at", sa.DateTime), sa.Column("compatibility_pct", sa.Float, server_default="0"), sa.Column("updated_at", sa.DateTime, server_default=sa.func.now(), onupdate=sa.func.now()))
    op.create_table("referral_programs", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("referrer_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("referee_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("code", sa.String(32), nullable=False), sa.Column("status", sa.String(16), server_default="pending"), sa.Column("referrer_reward", sa.Integer, server_default="0"), sa.Column("referee_reward", sa.Integer, server_default="0"), sa.Column("completed_at", sa.DateTime), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("chat_translations", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("chat_id", sa.BigInteger, sa.ForeignKey("chats.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("target_lang", sa.String(8), nullable=False), sa.Column("is_enabled", sa.Boolean, server_default=sa.text("true")), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))

    # Seasonal
    op.create_table("seasonal_events", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("name", sa.String(128), nullable=False), sa.Column("code", sa.String(32), unique=True, nullable=False), sa.Column("description", sa.Text), sa.Column("starts_at", sa.DateTime, nullable=False), sa.Column("ends_at", sa.DateTime, nullable=False), sa.Column("theme_color", sa.String(16), server_default="#f43f5e"), sa.Column("icon", sa.String(8)), sa.Column("bonus_multiplier", sa.Float, server_default="1.0"), sa.Column("special_features", JSONB), sa.Column("is_active", sa.Boolean, server_default=sa.text("true")))
    op.create_table("travel_modes", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False), sa.Column("current_city", sa.String(64)), sa.Column("current_country", sa.String(64)), sa.Column("current_lat", sa.Float), sa.Column("current_lon", sa.Float), sa.Column("started_at", sa.DateTime, server_default=sa.func.now()), sa.Column("expires_at", sa.DateTime), sa.Column("is_active", sa.Boolean, server_default=sa.text("true")))
    op.create_table("charity_donations", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("match_id", sa.BigInteger), sa.Column("amount_usd", sa.Float, nullable=False), sa.Column("charity", sa.String(128), nullable=False), sa.Column("transaction_hash", sa.String(128)), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("anonymous_profiles", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), unique=True, nullable=False), sa.Column("is_anonymous", sa.Boolean, server_default=sa.text("false")), sa.Column("anonymous_avatar", sa.String(512)), sa.Column("incognito_mode", sa.Boolean, server_default=sa.text("false")), sa.Column("hide_from_feed", sa.Boolean, server_default=sa.text("false")), sa.Column("hide_distance", sa.Boolean, server_default=sa.text("false")), sa.Column("hide_age", sa.Boolean, server_default=sa.text("false")), sa.Column("hide_last_seen", sa.Boolean, server_default=sa.text("false")))
    op.create_table("ab_tests", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("name", sa.String(128), unique=True, nullable=False), sa.Column("description", sa.Text), sa.Column("variants", JSONB, nullable=False), sa.Column("metrics", JSONB), sa.Column("is_active", sa.Boolean, server_default=sa.text("true")), sa.Column("starts_at", sa.DateTime, server_default=sa.func.now()), sa.Column("ends_at", sa.DateTime))
    op.create_table("ab_test_assignments", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("test_id", sa.Integer, sa.ForeignKey("ab_tests.id", ondelete="CASCADE"), nullable=False), sa.Column("variant", sa.String(64), nullable=False), sa.Column("assigned_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("ab_test_events", sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True), sa.Column("assignment_id", sa.BigInteger, sa.ForeignKey("ab_test_assignments.id", ondelete="CASCADE"), nullable=False, index=True), sa.Column("event_name", sa.String(64), nullable=False), sa.Column("value", sa.Float, server_default="0"), sa.Column("metadata_json", JSONB), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("subscription_plans", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("code", sa.String(32), unique=True, nullable=False), sa.Column("name", sa.String(64), nullable=False), sa.Column("tier", sa.Integer, server_default="1"), sa.Column("price_stars", sa.Integer, nullable=False), sa.Column("price_usd", sa.Float, nullable=False), sa.Column("duration_days", sa.Integer, server_default="30"), sa.Column("features", JSONB), sa.Column("boost_count", sa.Integer, server_default="0"), sa.Column("superlikes_per_day", sa.Integer, server_default="0"), sa.Column("is_vip", sa.Boolean, server_default=sa.text("false")), sa.Column("is_active", sa.Boolean, server_default=sa.text("true")))
    op.create_table("ad_campaigns", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("name", sa.String(128), nullable=False), sa.Column("advertiser", sa.String(128)), sa.Column("type", sa.String(32), server_default="banner"), sa.Column("image_url", sa.Text), sa.Column("target_url", sa.Text), sa.Column("target_regions", JSONB), sa.Column("target_age_min", sa.Integer, server_default="18"), sa.Column("target_age_max", sa.Integer, server_default="99"), sa.Column("target_genders", JSONB), sa.Column("impressions", sa.Integer, server_default="0"), sa.Column("clicks", sa.Integer, server_default="0"), sa.Column("is_active", sa.Boolean, server_default=sa.text("true")), sa.Column("starts_at", sa.DateTime, server_default=sa.func.now()), sa.Column("ends_at", sa.DateTime))
    op.create_table("sponsored_profiles", sa.Column("id", sa.Integer, primary_key=True, autoincrement=True), sa.Column("user_id", sa.BigInteger, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("budget_stars", sa.Integer, nullable=False), sa.Column("spent_stars", sa.Integer, server_default="0"), sa.Column("impressions", sa.Integer, server_default="0"), sa.Column("starts_at", sa.DateTime, server_default=sa.func.now()), sa.Column("ends_at", sa.DateTime), sa.Column("is_active", sa.Boolean, server_default=sa.text("true")))

    # Indexes
    op.create_index("ix_stories_expires", "stories", ["expires_at"])
    op.create_index("ix_coin_transactions_user_created", "coin_transactions", ["user_id", "created_at"])
    op.create_index("ix_chat_insights_last_message", "chat_insights", ["last_message_at"])


def downgrade() -> None:
    op.drop_table("sponsored_profiles")
    op.drop_table("ad_campaigns")
    op.drop_table("subscription_plans")
    op.drop_table("ab_test_events")
    op.drop_table("ab_test_assignments")
    op.drop_table("ab_tests")
    op.drop_table("anonymous_profiles")
    op.drop_table("charity_donations")
    op.drop_table("travel_modes")
    op.drop_table("seasonal_events")
    op.drop_table("chat_translations")
    op.drop_table("referral_programs")
    op.drop_table("chat_insights")
    op.drop_table("sentiment_analysis")
    op.drop_table("conversation_starters")
    op.drop_table("ai_recommendations")
    op.drop_table("translation_cache")
    op.drop_table("compatibility_scores")
    op.drop_table("photo_scores")
    op.drop_table("calls")
    op.drop_table("forwarded_messages")
    op.drop_table("saved_messages")
    op.drop_table("pinned_messages")
    op.drop_table("poll_votes")
    op.drop_table("polls")
    op.drop_table("scheduled_messages")
    op.drop_table("user_chat_themes")
    op.drop_table("chat_themes")
    op.drop_table("message_reactions")
    op.drop_table("user_sticker_packs")
    op.drop_table("stickers")
    op.drop_table("sticker_packs")
    op.drop_table("coin_packages")
    op.drop_table("nft_avatars")
    op.drop_table("live_streams")
    op.drop_table("forum_replies")
    op.drop_table("forum_threads")
    op.drop_table("event_attendees")
    op.drop_table("events")
    op.drop_table("group_posts")
    op.drop_table("group_members")
    op.drop_table("groups")
    op.drop_table("date_feedback")
    op.drop_table("date_plans")
    op.drop_table("data_export_requests")
    op.drop_table("stalker_protection")
    op.drop_table("panic_events")
    op.drop_table("safety_reports")
    op.drop_table("emergency_contacts")
    op.drop_table("two_factor_auth")
    op.drop_table("photo_verifications")
    op.drop_table("user_lifestyle_tags")
    op.drop_table("lifestyle_tags")
    op.drop_table("social_links")
    op.drop_table("video_intros")
    op.drop_table("voice_intros")
    op.drop_table("top_fives")
    op.drop_table("user_prompts")
    op.drop_table("prompts")
    op.drop_table("personality_tests")
    op.drop_table("leaderboard")
    op.drop_table("spin_rewards")
    op.drop_table("gift_transactions")
    op.drop_table("gifts")
    op.drop_table("user_missions")
    op.drop_table("missions")
    op.drop_table("streaks")
    op.drop_table("user_achievements")
    op.drop_table("achievements")
    op.drop_table("coin_transactions")
    op.drop_table("story_replies")
    op.drop_table("story_reactions")
    op.drop_table("story_views")
    op.drop_table("stories")
